[tool.bumpversion]
current_version = "0.1.3"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "flags4urfavecli.go"
search = "const Version = \"{current_version}\""
replace = "const Version = \"{new_version}\""
